FROM python:3.8-bullseye

COPY corrector_module/ /app/corrector_module

WORKDIR /app/corrector_module

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --user -r requirements.txt && \
    python setup.py install

RUN mkdir -p /var/log/xroad-metrics/corrector/logs
RUN mkdir -p /var/log/xroad-metrics/corrector/heartbeat

ENV PATH="/root/.local/bin:${PATH}"
ENV CORRECTOR_PASSWORD=default

RUN mkdir -p /etc/xroad-metrics/corrector/

COPY files/corrector/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

WORKDIR /app/corrector_module/bin
CMD xroad-metrics-correctord

